# -*- coding: utf-8 -*-
"""Version 3 Lab — Experiment Registry."""
from __future__ import annotations

from typing import Any

from .taxonomy import CONTROL_CORPUS_SIZE, CONTROL_HIT

REGISTRY: dict[str, dict[str, Any]] = {
    "v3-p1-lab-harness": {
        "experiment_id": "v3-p1-lab-harness",
        "phase": "P1",
        "flag": "F_V3_LAB_ENABLED",
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "Lab pipeline stubs only (identity when flags OFF)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0",
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
    },
    "v3-p2-representation": {
        "experiment_id": "v3-p2-representation",
        "phase": "P2",
        "flag": "F_V3_REPRESENTATION",
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "Feature Generator + Representation Contract 2.0 (Evaluation still stub)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0 (not claimed until Ranking)",
        "parity_gate": "Hit == Control AND churn_hit = 0",
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "contract": "v3-lab-representation/2.0",
        "representation_id": "v3-rep-p2-v1",
    },
    "v3-p3-admission": {
        "experiment_id": "v3-p3-admission",
        "phase": "P3",
        "flag": "F_V3_ADMISSION",
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "AP-V3-A Banded Deep Admit (Selection/Evaluation still stub)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0 (not claimed; Evaluation stub)",
        "parity_gate": "Hit == Control AND churn_hit = 0",
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "contract": "v3-lab-admission/2.0",
        "admission_id": "v3-adm-p3-v1",
        "policy_id": "AP-V3-A-banded-deep",
    },
    "v3-p4-selection": {
        "experiment_id": "v3-p4-selection",
        "phase": "P4",
        "flag": "F_V3_SELECTION",
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "SEL-V3-RO Reorder-only (Evaluation/Purchase still stub)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0 (not claimed; Evaluation stub)",
        "parity_gate": "Hit == Control AND churn_hit = 0",
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "contract": "v3-lab-selection/2.0",
        "selection_id": "v3-sel-p4-v1",
        "policy_id": "SEL-V3-RO",
    },
    "v3-p5-freeze": {
        "experiment_id": "v3-p5-freeze",
        "phase": "P5",
        "flag": None,
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "Lab foundation freeze (no new algorithm)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "baseline_id": "v3-lab-baseline-p5-v1",
        "freeze_id": "v3-lab-freeze/1.0",
    },
    "v3-rank-d1-recal-285r-ab": {
        "experiment_id": "v3-rank-d1-recal-285r-ab",
        "phase": "A-01",
        "flag": "F_V3_RANK_D1_ENABLED",
        "alias_of": "v3-a01-d1-recal",
        "status": "lab_primary_candidate",
        "candidate_rank": 1,
        "frozen": True,
        "accuracy_intervention": True,
        "contract": "v3-lab-evaluation/2.0",
        "evaluation_id": "v3-eval-a01-d1",
        "policy_id": "D1-Recalibrator",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0",
    },
    "v3-a01-d1-recal": {
        "experiment_id": "v3-a01-d1-recal",
        "phase": "A-01",
        "flag": "F_V3_RANK_D1_ENABLED",
        "control": f"V2 Final (PE-V2-A) Hit={CONTROL_HIT}",
        "treatment": "D1 Recalibrator (Evaluation only)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0",
        "status": "lab_primary_evaluation",
        "candidate_rank": 1,
        "frozen": True,
        "accuracy_intervention": True,
        "contract": "v3-lab-evaluation/2.0",
        "evaluation_id": "v3-eval-a01-d1",
        "policy_id": "D1-Recalibrator",
        "lab_hit": 246,
        "validation": "PASS",
        "in_adopted_stack": True,
        "production_wiring": False,
        "note": "Lab Configuration Freeze — Evaluation Primary in A-01+A-03 stack",
    },
    "v3-rank-d2-rerank-285r-ab": {
        "experiment_id": "v3-rank-d2-rerank-285r-ab",
        "phase": "A-02",
        "flag": "F_V3_RANK_D2_ENABLED",
        "alias_of": "v3-a02-d2-rerank",
        "status": "lab_secondary_candidate",
        "candidate_rank": 2,
        "frozen": True,
        "accuracy_intervention": True,
        "contract": "v3-lab-evaluation/2.1",
        "evaluation_id": "v3-eval-a02-d2",
        "policy_id": "D2-Reranker",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0",
    },
    "v3-a02-d2-rerank": {
        "experiment_id": "v3-a02-d2-rerank",
        "phase": "A-02",
        "flag": "F_V3_RANK_D2_ENABLED",
        "control": f"Lab Baseline Hit={CONTROL_HIT}",
        "treatment": "D2 Listwise Reranker (Evaluation only; independent of A-01)",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": f"Hit > {CONTROL_HIT} AND churn_hit = 0",
        "status": "lab_secondary_candidate",
        "candidate_rank": 2,
        "frozen": True,
        "accuracy_intervention": True,
        "contract": "v3-lab-evaluation/2.1",
        "evaluation_id": "v3-eval-a02-d2",
        "policy_id": "D2-Reranker",
        "lab_hit": 242,
        "validation": "Lab PASS only",
        "in_adopted_stack": False,
        "production_wiring": False,
        "compare_to": ["lab_baseline_218", "a01_hit_246"],
        "note": "Lab Configuration Freeze — Secondary Candidate held; not in A-01+A-03 stack",
    },
    "v3-accuracy-candidate-review": {
        "experiment_id": "v3-accuracy-candidate-review",
        "phase": "Accuracy Phase 1",
        "flag": None,
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "decision": "A-01 primary > A-02 secondary",
        "report": "docs/releases/v3-accuracy-candidate-review.md",
    },
    "v3-accuracy-phase1-close": {
        "experiment_id": "v3-accuracy-phase1-close",
        "phase": "Accuracy Phase 1",
        "flag": None,
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "close_id": "v3-accuracy-phase1-close/1.0",
        "primary_candidate": "A-01",
        "secondary_candidate": "A-02",
        "baseline_unchanged": True,
        "production_wiring": False,
        "report": "docs/releases/v3-accuracy-phase1-final-report.md",
    },
    "v3-accuracy-phase2-research-design": {
        "experiment_id": "v3-accuracy-phase2-research-design",
        "phase": "Accuracy Phase 2",
        "flag": None,
        "status": "design_complete",
        "frozen": True,
        "accuracy_intervention": False,
        "implementation": False,
        "primary_problem": "I-Pool",
        "a03_status": "implemented_via_v3-a03-pool-coverage",
        "report": "docs/releases/v3-accuracy-phase2-research-report.md",
        "roadmap": "docs/releases/v3-accuracy-phase2-research-roadmap.md",
    },
    "v3-a03-pool-coverage": {
        "experiment_id": "v3-a03-pool-coverage",
        "phase": "A-03",
        "flag": "F_V3_A03_POOL_ADMIT_ENABLED",
        "control": "A-01 Primary ON (Hit 246)",
        "treatment": "A-01 ON + A-03 Pool Coverage Admission",
        "corpus": f"{CONTROL_CORPUS_SIZE}R",
        "hard_gate": "Hit > 246 AND churn_hit = 0",
        "status": "lab_primary_admission",
        "frozen": True,
        "accuracy_intervention": True,
        "stage": "Admission",
        "contract": "v3-lab-admission/2.1",
        "admission_id": "v3-adm-a03-v1",
        "policy_id": "AP-V3-A03-pool-coverage",
        "target": "I-Pool",
        "representation_unchanged": True,
        "evaluation_unchanged": True,
        "lab_hit": 255,
        "validation": "PASS",
        "in_adopted_stack": True,
        "production_wiring": False,
    },
    "v3-a05-favorite-safe-coverage": {
        "experiment_id": "v3-a05-favorite-safe-coverage",
        "phase": "A-05",
        "flag": "F_V3_A05_ADM_FAVSAFE_ENABLED",
        "control": "Lab Flag OFF (identity top-1)",
        "treatment": "A-05 Favorite-Safe Coverage Admission",
        "contrast": "A-03 Pool Coverage (frozen)",
        "corpus": "Lab Accuracy 285R + Offline real 285R",
        "hard_gate": "Offline: worsened_winner_rank1=0 AND ΔHit>0",
        "status": "implemented",
        "frozen": False,
        "accuracy_intervention": True,
        "stage": "Admission",
        "contract": "v3-lab-admission/2.2",
        "admission_id": "v3-adm-a05-v1",
        "policy_id": "AP-V3-A05-favorite-safe-coverage",
        "target": "I-Pool-favorite-safe",
        "a03_unchanged": True,
        "representation_unchanged": True,
        "evaluation_unchanged": True,
        "selection_unchanged": True,
        "production_wiring": False,
        "default_flag_off": True,
        "mutex_with": "F_V3_A03_POOL_ADMIT_ENABLED",
        "validation": "PASS",
        "shadow_implementation": True,
        "shadow_evaluation_started": False,
    },
    "v3-a05-shadow": {
        "experiment_id": "v3-a05-shadow",
        "phase": "A-05-Shadow",
        "flag": "F_V3_A05_ADM_FAVSAFE_ENABLED",
        "shadow_runtime_env": "WIN5_V3_A05_SHADOW_RUNTIME_ENABLED",
        "status": "implemented",
        "evaluation_window_started": False,
        "production_wiring": False,
        "default_flag_off": True,
        "package": "research/v3_lab/shadow",
        "report": "docs/releases/v3-a05-shadow-implementation.md",
    },
    "v3-lab-configuration-freeze": {
        "experiment_id": "v3-lab-configuration-freeze",
        "phase": "Lab Configuration Freeze",
        "flag": None,
        "status": "complete",
        "frozen": True,
        "accuracy_intervention": False,
        "freeze_id": "v3-lab-configuration-freeze/1.0",
        "baseline_id": "v3-lab-baseline-v2-a01-a03",
        "adopted_stack": ["A-03 Admission", "A-01 Evaluation"],
        "a02_held_secondary": True,
        "production_wiring": False,
        "report": "docs/releases/v3-lab-configuration-report.md",
    },
    "v3-ap-banded-deep-285r-ab": {
        "experiment_id": "v3-ap-banded-deep-285r-ab",
        "phase": "P3",
        "flag": "F_V3_ADMISSION",
        "status": "implemented_via_v3-p3-admission",
        "frozen": True,
        "accuracy_intervention": False,
        "alias_of": "v3-p3-admission",
    },
    "v3-ap-coverage-285r-ab": {
        "experiment_id": "v3-ap-coverage-285r-ab",
        "phase": "P3",
        "flag": "F_V3_AP_COVERAGE_ENABLED",
        "status": "reserved",
        "frozen": True,
        "accuracy_intervention": True,
    },
    "v3-sel-reorder-285r-ab": {
        "experiment_id": "v3-sel-reorder-285r-ab",
        "phase": "P4",
        "flag": "F_V3_SELECTION",
        "status": "implemented_via_v3-p4-selection",
        "frozen": True,
        "accuracy_intervention": False,
        "alias_of": "v3-p4-selection",
    },
}

# P5: registry is append-only for new Accuracy experiments after separate approval.
REGISTRY_FROZEN = True


def list_experiments(*, phase: str | None = None) -> list[dict[str, Any]]:
    rows = list(REGISTRY.values())
    if phase:
        rows = [r for r in rows if r.get("phase") == phase]
    return rows


def get_experiment(experiment_id: str) -> dict[str, Any] | None:
    return REGISTRY.get(experiment_id)


__all__ = ["REGISTRY", "REGISTRY_FROZEN", "list_experiments", "get_experiment"]
