#!/usr/bin/env python3
"""Regenerate expected SHA256s from v5 file_sha256.txt + actual files.

Do not hand-type deploy-file hashes. Re-run this after replacing
v5_reference files, then rebuild OWNER_LIVE_COMPARE.sh.
Canon: code-deploy review v6 deploy_files + file SHA.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

PACK = Path(__file__).resolve().parent
REF = PACK / "v5_reference"
FILES = REF / "files" / "services" / "win5-ai"
FILE_SHA256 = REF / "file_sha256.txt"
DEPLOY_FILES = REF / "deploy_files.txt"
ORIGIN_MAIN = REF / "origin_main_sha256.txt"
LIVE_COMPARE = PACK / "live_compare.py"
EXPECTED_OUT = PACK / "01_docs" / "expected_hashes.txt"
HEX64 = re.compile(r"^[0-9a-f]{64}$")
BEGIN = "# BEGIN GENERATED_HASHES"
END = "# END GENERATED_HASHES"

DEPLOY_RELS = (
    "app/main.py",
    "app/data/db.py",
    "app/data/repository/__init__.py",
    "app/core/feature_loader_bridge.py",
    "app/data/migrations/022_prediction_run_idempotency.sql",
    "app/predictions/__init__.py",
    "app/predictions/guards.py",
    "app/predictions/runs.py",
    "app/predictions/feature_pin.py",
    "app/predictions/provenance.py",
    "app/predictions/snapshot.py",
)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_sha_listing(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        digest, rel = line.split(None, 1)
        if not HEX64.match(digest):
            raise SystemExit("non-hex64 in %s: %s %s" % (path.name, digest, rel))
        out[rel] = digest
    return out


def deploy_rels_from_listing() -> list[str]:
    rels: list[str] = []
    excluded = False
    for raw in DEPLOY_FILES.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("Excluded"):
            excluded = True
            continue
        if excluded or not line.startswith("services/win5-ai/"):
            continue
        rels.append(line[len("services/win5-ai/") :])
    if tuple(rels) != DEPLOY_RELS:
        raise SystemExit("deploy_files.txt parse mismatch: %s" % (rels,))
    return rels


def load_origin_main() -> tuple[str, str]:
    listing = parse_sha_listing(ORIGIN_MAIN)
    main = listing["services/win5-ai/app/main.py"]
    db = listing["services/win5-ai/app/data/db.py"]
    return main, db


def collect() -> dict[str, object]:
    rels = deploy_rels_from_listing()
    listed = parse_sha_listing(FILE_SHA256)
    deploy: dict[str, str] = {}
    for rel in rels:
        path = FILES / rel
        if not path.is_file():
            raise SystemExit("missing v5 reference file: %s" % path)
        digest = sha256_file(path)
        if not HEX64.match(digest):
            raise SystemExit("generated digest not 64 hex: %s %s" % (rel, digest))
        listed_key = "services/win5-ai/" + rel
        if listed_key not in listed:
            raise SystemExit("not in file_sha256.txt: %s" % listed_key)
        if listed[listed_key] != digest:
            raise SystemExit(
                "file_sha256.txt != actual file: %s listed=%s file=%s"
                % (rel, listed[listed_key], digest)
            )
        deploy[rel] = digest
    if len(deploy) != 11:
        raise SystemExit("expected 11 deploy hashes, got %s" % len(deploy))
    main_base, db_origin = load_origin_main()
    return {
        "MAIN_BASE": main_base,
        "MAIN_CANDIDATE": deploy["app/main.py"],
        "DB_ORIGIN_MAIN": db_origin,
        "DB_CANDIDATE": deploy["app/data/db.py"],
        "DEPLOY": deploy,
    }


def render_block(data: dict[str, object]) -> str:
    lines = [
        BEGIN,
        "# Generated by generate_hashes.py from v5_reference/file_sha256.txt and v5_reference/files.",
        "# Do not hand-edit this block.",
        'MAIN_BASE = "%s"' % data["MAIN_BASE"],
        'MAIN_CANDIDATE = "%s"' % data["MAIN_CANDIDATE"],
        'DB_ORIGIN_MAIN = "%s"' % data["DB_ORIGIN_MAIN"],
        'DB_CANDIDATE = "%s"' % data["DB_CANDIDATE"],
        "DEPLOY = {",
    ]
    deploy = data["DEPLOY"]
    assert isinstance(deploy, dict)
    for rel, digest in deploy.items():
        lines.append('    "%s": "%s",' % (rel, digest))
    lines.append("}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def write_expected_hashes(data: dict[str, object]) -> None:
    deploy = data["DEPLOY"]
    assert isinstance(deploy, dict)
    lines = [
        "v5 expected hashes — generated from code-deploy review v6",
        "========================================================",
        "",
        "Source: v5_reference/file_sha256.txt matched to v5_reference/files.",
        "Canon: production_disabled_post_code_deploy_review_v6_20260912",
        "Generator: generate_hashes.py",
        "",
        "origin/main 25a3f88 from v5_reference/origin_main_sha256.txt",
        "  services/win5-ai/app/main.py",
        "    %s" % data["MAIN_BASE"],
        "  services/win5-ai/app/data/db.py",
        "    %s" % data["DB_ORIGIN_MAIN"],
        "",
        "v6 deploy_files candidates (%d):" % len(deploy),
    ]
    for rel, digest in deploy.items():
        lines.append("  %s" % rel)
        lines.append("    %s" % digest)
    lines.append("")
    EXPECTED_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def patch_live_compare(block: str) -> None:
    text = LIVE_COMPARE.read_text(encoding="utf-8")
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < 0 or end <= start:
        raise SystemExit("generated hash markers missing in live_compare.py")
    end += len(END)
    if text[end : end + 1] == "\n":
        end += 1
    LIVE_COMPARE.write_text(text[:start] + block + text[end:], encoding="utf-8")


def main() -> int:
    data = collect()
    write_expected_hashes(data)
    patch_live_compare(render_block(data))
    print("GENERATED_DEPLOY_HASHES=%d" % len(data["DEPLOY"]))  # type: ignore[arg-type]
    print("SNAPSHOT_PY=%s" % data["DEPLOY"]["app/predictions/snapshot.py"])  # type: ignore[index]
    return 0


if __name__ == "__main__":
    sys.exit(main())
