#!/usr/bin/env python3
"""Regenerate origin/main and review v6 SHA256s from reference/ files.

Do not hand-type the six hashes. Re-run this after replacing reference files.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

PACK = Path(__file__).resolve().parent
ORIGIN_DIR = PACK / "reference" / "origin_main_25a3f88"
V6_DIR = PACK / "reference" / "review_v6"
THREE_WAY = PACK / "three_way_diff.py"
EXPECTED_OUT = PACK / "01_docs" / "expected_hashes.txt"
ORIGIN_LISTING = PACK / "reference" / "origin_main_sha256.txt"
V6_LISTING = PACK / "reference" / "review_v6_sha256.txt"
HEX64 = re.compile(r"^[0-9a-f]{64}$")
BEGIN = "# BEGIN GENERATED_HASHES"
END = "# END GENERATED_HASHES"
CAPTURE_RELS = (
    "app/main.py",
    "app/data/repository/__init__.py",
    "app/core/feature_loader_bridge.py",
)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def collect_side(root: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for rel in CAPTURE_RELS:
        path = root / rel
        if not path.is_file():
            raise SystemExit("missing reference file: %s" % path)
        digest = sha256_file(path)
        if not HEX64.match(digest):
            raise SystemExit("generated digest not 64 hex: %s %s" % (rel, digest))
        out[rel] = digest
    return out


def write_listing(path: Path, mapping: dict[str, str], header: str) -> None:
    lines = [header, ""]
    for rel, digest in mapping.items():
        lines.append("%s  %s" % (digest, rel))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_block(origin: dict[str, str], v6: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "# Generated by generate_hashes.py from reference/ files.",
        "# Do not hand-edit this block.",
        "ORIGIN = {",
    ]
    for rel, digest in origin.items():
        lines.append('    "%s": "%s",' % (rel, digest))
    lines.append("}")
    lines.append("V6 = {")
    for rel, digest in v6.items():
        lines.append('    "%s": "%s",' % (rel, digest))
    lines.append("}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def write_expected(origin: dict[str, str], v6: dict[str, str]) -> None:
    lines = [
        "Expected hashes — generated from bundled reference files",
        "=======================================================",
        "",
        "origin/main 25a3f88b8aab61a5462c06efa133b21865ef6083",
        "source tar SHA256=d1e6b5847f1387d696d39b87ad0dbfa4e44f8322ad1caecb75ce0969bad5edff",
        "",
    ]
    for rel, digest in origin.items():
        lines.append("  %s" % rel)
        lines.append("    %s" % digest)
    lines.extend(
        [
            "",
            "code-deploy review v6 candidates",
            "ZIP SHA256=548b274facc2b4f8ffba8b854a6e009d8b7455fb816dcde9550eb9b364329373",
            "",
        ]
    )
    for rel, digest in v6.items():
        lines.append("  %s" % rel)
        lines.append("    %s" % digest)
    lines.append("")
    EXPECTED_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def patch_three_way(block: str) -> None:
    text = THREE_WAY.read_text(encoding="utf-8")
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < 0 or end <= start:
        raise SystemExit("generated hash markers missing in three_way_diff.py")
    end += len(END)
    if text[end : end + 1] == "\n":
        end += 1
    THREE_WAY.write_text(text[:start] + block + text[end:], encoding="utf-8")


def main() -> int:
    origin = collect_side(ORIGIN_DIR)
    v6 = collect_side(V6_DIR)
    write_listing(
        ORIGIN_LISTING,
        origin,
        "origin/main 25a3f88b8aab61a5462c06efa133b21865ef6083",
    )
    write_listing(
        V6_LISTING,
        v6,
        "code-deploy review v6 candidates",
    )
    write_expected(origin, v6)
    patch_three_way(render_block(origin, v6))
    print("GENERATED_ORIGIN_HASHES=%d" % len(origin))
    print("GENERATED_V6_HASHES=%d" % len(v6))
    return 0


if __name__ == "__main__":
    sys.exit(main())
