#!/usr/bin/env python3
"""Local 3-way: origin/main 25a3f88 vs Production live vs review v6.

Review-machine only. Does not SSH. Does not write Production.
Does not create a deploy execution pack.
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
from pathlib import Path

PACK = Path(__file__).resolve().parent
ORIGIN_DIR = PACK / "reference" / "origin_main_25a3f88"
V6_DIR = PACK / "reference" / "review_v6"
CAPTURE_RELS = (
    "app/main.py",
    "app/data/repository/__init__.py",
    "app/core/feature_loader_bridge.py",
)
ORIGIN_MAIN_COMMIT = "25a3f88b8aab61a5462c06efa133b21865ef6083"

# BEGIN GENERATED_HASHES
# Generated by generate_hashes.py from reference/ files.
# Do not hand-edit this block.
ORIGIN = {
    "app/main.py": "a54f1eaa5b8540c2f08d8b0e656a3ccbb78142d4d1cb2c8951e4105f3630184e",
    "app/data/repository/__init__.py": "557713a95b0e9f5a8f798eeb5e525c85adab3063b2e6529ee0be2155bb29992b",
    "app/core/feature_loader_bridge.py": "e06e6ee971e2ae8d07bbcee4501ab9024052de52dd119ea007cb71481ae5272e",
}
V6 = {
    "app/main.py": "7577973c16eb7aad395cd11acae3c8ef987a3c0533924c1994ae32afeaf818e5",
    "app/data/repository/__init__.py": "9624699ec48d2af8b1fdc24ac81b8ae436c77ffa92a7f0b1378ecd17248b4c08",
    "app/core/feature_loader_bridge.py": "f3c25c7b87941138555158e051d0520fc705889e8a2a17e8889c7fc5325eae44",
}
# END GENERATED_HASHES


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def out(msg: str) -> None:
    print(msg)


def classify(live: str | None, origin: str, v6: str) -> str:
    if live is None:
        return "ABSENT"
    if live == origin:
        return "MATCH_ORIGIN_MAIN"
    if live == v6:
        return "MATCH_V6"
    return "DIVERGENT"


def unified(left_label: str, right_label: str, left: bytes, right: bytes) -> list[str]:
    left_lines = left.decode("utf-8", "replace").splitlines()
    right_lines = right.decode("utf-8", "replace").splitlines()
    return list(
        difflib.unified_diff(
            left_lines,
            right_lines,
            fromfile=left_label,
            tofile=right_label,
            lineterm="",
        )
    )


def load_side(root: Path, rel: str) -> tuple[bytes | None, str | None, int | None]:
    path = root / rel
    if not path.is_file():
        return None, None, None
    data = path.read_bytes()
    return data, hashlib.sha256(data).hexdigest(), len(data)


def run_three_way(live_root: Path) -> int:
    out("PACK=production_disabled_post_live_source_capture_readonly_v3_20260912")
    out("KIND=LOCAL_THREE_WAY_AFTER_CAPTURE")
    out("ORIGIN_MAIN_COMMIT=%s" % ORIGIN_MAIN_COMMIT)
    out("LIVE_ROOT=%s" % live_root)
    out("PRODUCTION_CODE_DEPLOY_ALLOWED=NO")
    out("OWNER_DEPLOY_APPROVED=NO")
    out("POST_CODE_PRODUCTION_DEPLOYED=NO")
    out("THREE_WAY_IS_NOT_DEPLOY_APPROVAL=YES")
    out("DEPLOY_EXECUTION_PACK=NO")
    out("WHOLESALE_REPLACE=NO")
    missing = [rel for rel in CAPTURE_RELS if not (live_root / rel).is_file()]
    if len(missing) == len(CAPTURE_RELS):
        out("CAPTURE_RETURNED=NO")
        out("THREE_WAY_RESULT=SKIPPED_NO_LIVE")
        return 0
    out("CAPTURE_RETURNED=YES")
    classes: dict[str, str] = {}
    for rel in CAPTURE_RELS:
        origin_data, origin_sha, origin_size = load_side(ORIGIN_DIR, rel)
        v6_data, v6_sha, v6_size = load_side(V6_DIR, rel)
        live_data, live_sha, live_size = load_side(live_root, rel)
        if origin_sha != ORIGIN[rel] or v6_sha != V6[rel]:
            out("REFERENCE_MISMATCH=%s" % rel)
            return 2
        klass = classify(live_sha, ORIGIN[rel], V6[rel])
        classes[rel] = klass
        out("----- %s -----" % rel)
        out("ORIGIN_MAIN_SHA256=%s" % origin_sha)
        out("ORIGIN_MAIN_SIZE=%s" % origin_size)
        out("PRODUCTION_LIVE_SHA256=%s" % (live_sha or "ABSENT"))
        out("PRODUCTION_LIVE_SIZE=%s" % (live_size if live_size is not None else "ABSENT"))
        out("REVIEW_V6_SHA256=%s" % v6_sha)
        out("REVIEW_V6_SIZE=%s" % v6_size)
        out("LIVE_VS_ORIGIN=%s" % ("MATCH" if live_sha == origin_sha else "DIFFER"))
        out("LIVE_VS_V6=%s" % ("MATCH" if live_sha == v6_sha else "DIFFER"))
        out("CLASS=%s" % klass)
        if rel == "app/main.py":
            if klass == "DIVERGENT":
                out("MAIN_PY_WHOLESALE_REPLACE_ALLOWED=NO")
                out("MAIN_PY_LATER_MODE=HUNK_ONLY")
            elif klass == "MATCH_ORIGIN_MAIN":
                out("MAIN_PY_WHOLESALE_REPLACE_ALLOWED=NO_UNTIL_DEPLOY_PACK")
                out("MAIN_PY_LATER_MODE=HUNK_OR_FILE_AGAINST_ORIGIN_MAIN")
            elif klass == "MATCH_V6":
                out("MAIN_PY_WHOLESALE_REPLACE_ALLOWED=NO")
                out("MAIN_PY_LATER_MODE=ALREADY_CANDIDATE")
            else:
                out("MAIN_PY_WHOLESALE_REPLACE_ALLOWED=NO")
                out("MAIN_PY_LATER_MODE=ABSENT")
        if live_data is not None and origin_data is not None:
            diff = unified("origin/main:%s" % rel, "production-live:%s" % rel, origin_data, live_data)
            out("DIFF_ORIGIN_VS_LIVE_LINES=%s" % len(diff))
            for line in diff:
                out(line)
        if live_data is not None and v6_data is not None:
            diff = unified("production-live:%s" % rel, "review-v6:%s" % rel, live_data, v6_data)
            out("DIFF_LIVE_VS_V6_LINES=%s" % len(diff))
            for line in diff:
                out(line)
        if origin_data is not None and v6_data is not None:
            diff = unified("origin/main:%s" % rel, "review-v6:%s" % rel, origin_data, v6_data)
            out("DIFF_ORIGIN_VS_V6_LINES=%s" % len(diff))
            for line in diff:
                out(line)
    out("----- judgment -----")
    for rel, klass in classes.items():
        out("THREE_WAY_CLASS %s %s" % (rel, klass))
    if classes.get("app/main.py") == "DIVERGENT":
        out("NOTE=live main.py is DIVERGENT; later deploy must be hunk-only")
    out("THREE_WAY_RESULT=DONE")
    out("PRODUCTION_CODE_DEPLOY_ALLOWED=NO")
    out("DEPLOY_EXECUTION_PACK=NO")
    out("NEXT_STEP=RETURN_THREE_WAY_TO_CURSOR_DO_NOT_DEPLOY")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Local 3-way after Owner capture return")
    parser.add_argument(
        "--live",
        default="",
        help="Directory containing the three captured live files (Windows/review only)",
    )
    args = parser.parse_args(argv)
    out("PACK=production_disabled_post_live_source_capture_readonly_v3_20260912")
    if not args.live:
        out("CAPTURE_RETURNED=NO")
        out("THREE_WAY_RESULT=SKIPPED_NO_LIVE")
        out("PRODUCTION_CODE_DEPLOY_ALLOWED=NO")
        out("DEPLOY_EXECUTION_PACK=NO")
        return 0
    live_root = Path(args.live)
    if not live_root.is_dir():
        out("CAPTURE_RETURNED=NO")
        out("LIVE_DIR=ABSENT")
        out("THREE_WAY_RESULT=SKIPPED_NO_LIVE")
        return 0
    return run_three_way(live_root)


if __name__ == "__main__":
    sys.exit(main())
